version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"  
    environment:
      DB_HOST: postgres  
      DB_USER: postgres
      DB_PASSWORD: postgres
